#!/bin/bash
#
# This script is called when "snapper rollback" is executed.
# It should stay in /usr/lib/snapper/plugins/rollback
#
# Arguments: old_snapshot new_snapshot
#
# the old snapshot is read-only, the new snapshot is read-write
#

VARDIR=/var/lib/rollback
OLD=$1
NEW=$2

test -d $NEW/$VARDIR || mkdir -p $NEW/$VARDIR/
touch $NEW/$VARDIR/check-registration
